import { Racing_Sans_One } from 'next/font/google';
import { Roboto } from "next/font/google";
import "./globals.css";

const racingSansOne = Racing_Sans_One({
  weight: '400',
  subsets: ['latin'],
  display: 'swap',
});

const font = Roboto({
  variable: "--font",
  subsets: ["latin"],
});

export const metadata = {
  title: "My Mockup App",
  description: "Generated by create next app",
  icons: {
    icon: "/icons/favicon.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={racingSansOne.className}>
      <body className={`${font.variable} `}>
        {children}
      </body>
    </html>
  );
}
